#!/bin/bash
# =============================================================================
# run_profile.sh  —  Step 0: Run kernel on real NPU + capture msprof data
# =============================================================================
# Environment   : triton_profiling (CANN 8.5) — dedicated profiling container
#                 Host driver 25.5.1; msprof CANN 9 compatibility issue
# Kernel        : chunk_kda_bwd_kernel_wy_dqkg_fused_opt_v2
# Output        : scripts/e2e_chunk/output/op_summary.csv
#
# This step MUST run on a machine with physical Ascend NPU hardware.
# The msprof tool captures per-pipe busy times (aic_mac_time, aiv_vec_time,
# aiv_scalar_time, etc.) which are essential for calibration.
#
# Usage:
#   chmod +x scripts/e2e_chunk/run_profile.sh
#   cd /home/triton_sim/vTriton
#   bash scripts/e2e_chunk/run_profile.sh
# =============================================================================
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT_DIR"

OUT_DIR="$ROOT_DIR/scripts/e2e_chunk/output"
mkdir -p "$OUT_DIR"

# ── CANN environment ────────────────────────────────────────────────────────
ASCEND_TOOLKIT="/usr/local/Ascend/ascend-toolkit"
if [ -f "$ASCEND_TOOLKIT/set_env.sh" ]; then
    . "$ASCEND_TOOLKIT/set_env.sh"
else
    echo "[ERROR] CANN toolkit not found at $ASCEND_TOOLKIT"
    exit 1
fi

MSPROF=$(which msprof 2>/dev/null || true)
if [ -z "$MSPROF" ]; then
    echo "[ERROR] msprof not in PATH. Check CANN installation."
    exit 1
fi
echo "[CHECK] msprof: $MSPROF"

# ── Verify NPU is accessible ────────────────────────────────────────────────
if ! npu-smi info 2>/dev/null | grep -q 'Status.*OK'; then
    echo "[ERROR] No NPU device found or driver not ready."
    echo "  This step requires physical Ascend 910B NPU hardware."
    echo "  npu-smi info output:"
    npu-smi info 2>&1 || true
    exit 1
fi
echo "[CHECK] NPU device OK"

# ── Output directory for msprof data ────────────────────────────────────────
MSPROF_DIR="$ROOT_DIR/scripts/e2e_chunk/msprof_data"
rm -rf "$MSPROF_DIR"
mkdir -p "$MSPROF_DIR"

# ── Run kernel under msprof ─────────────────────────────────────────────────
echo ""
echo "============================================================"
echo "  STEP 0: RUN KERNEL + CAPTURE msprof PROFILING DATA"
echo "============================================================"
echo "  Kernel : chunk_kda_bwd_kernel_wy_dqkg_fused_opt_v2"
echo "  Output : $MSPROF_DIR"
echo "============================================================"
echo ""

msprof \
    --output="$MSPROF_DIR" \
    --aic-metrics=PipeUtilization \
    --ai-core=on \
    --aic-mode=task-based \
    --task-time=on \
    python3 \
        "$ROOT_DIR/test/chunk_kda_bwd_kernel_wy_dqkg_fused_opt_v2.py" \
    2>&1 | tee "$OUT_DIR/profile_log.txt"
MSPROF_RC=${PIPESTATUS[0]}

if [ $MSPROF_RC -ne 0 ]; then
    echo ""
    echo "[ERROR] msprof exited with code $MSPROF_RC"
    echo "  Check $OUT_DIR/profile_log.txt"
    exit 1
fi

# ── Extract op_summary.csv ──────────────────────────────────────────────────
OP_SUMMARY=$(find "$MSPROF_DIR" -name 'op_summary*.csv' 2>/dev/null | head -1)
if [ -z "$OP_SUMMARY" ]; then
    echo ""
    echo "[ERROR] No op_summary.csv generated by msprof."
    echo "  Directory contents:"
    find "$MSPROF_DIR" -type f 2>/dev/null | head -20
    exit 1
fi

cp "$OP_SUMMARY" "$OUT_DIR/op_summary.csv"
echo ""
echo "============================================================"
echo "  PROFILING OUTPUT"
echo "============================================================"
echo "  Raw:    $MSPROF_DIR"
echo "  Copied: $OUT_DIR/op_summary.csv"
echo ""
echo "  Chunk kernel entries:"
grep -c "chunk_kda" "$OUT_DIR/op_summary.csv" 2>/dev/null || echo "  0"
echo ""
echo "[DONE] → Next: bash scripts/e2e_chunk/run_dump_mlir.sh"
